### ISSUE TITLE
Idea/Enhancement

### ISSUE THREAD

**Issue by FreshImmuc** [SharezoneApp/sharezone-client#1]
Fügt bitte die Option zum hinzufügen von Noten usw hinzu. Ausserdem: Fügt einen Strich auf dem Stundenplan hinzu, der immer die genaue Zeit anzeigt.

**Comment by nilsreichardt** [comment]
Hi @FreshImmuc, vielen Dank für dein Ticket! 🙂 Dieses Repo werden wir wahrscheinlich nicht mehr verwenden, weil wir bereits ein anderes GitHub in Vorbereitung haben. Falls unsere Vorbereitungen abgeschlossen, werden wir dein Ticket in das neue Repo verschieben 👍

Falls du direkt benachrichtigt werden möchtest, wenn es so weit ist, kannst du uns gerne auf Discord folgen: https://sharezone.net/discord
